import Header from "@/components/header/header";
import Sidebar from "@/components/sidebar/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        <Sidebar />
        <main className="w-full">
          <div className="w-full lg:w-[82%] lg:ml-auto">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
